[package]
name = "lfs"
version = "2.1.0-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2021"
keywords = ["linux", "filesystem", "fs"]
license = "MIT"
categories = ["filesystem", "command-line-utilities"]
description = "give information on mounted filesystems"
repository = "https://github.com/Canop/lfs"
readme = "README.md"
rust-version = "1.56"

[dependencies]
argh = "0.1.7"
crossterm = "0.22.1"
file-size = "1.0.3"
lfs-core = "0.9.0"
serde = "1.0"
serde_json = "1.0"
termimad = "0.20.0"

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# lfs-core = { path = "../lfs-core" }
